#!/usr/bin/env python3
"""Qwen Model Fallback Rotator for opencode.

Rotates through 81 free-tier Qwen LLM models when quota is exhausted.
Generates opencode.json from template.

Usage:
    python scripts/qwen_fallback.py --status       # Probe all models
    python scripts/qwen_fallback.py --rotate       # Rotate to next model
    python scripts/qwen_fallback.py --track        # Update tracking doc
    python scripts/qwen_fallback.py --model M      # Set model directly
"""

import argparse
import json
import os
import sys
from dataclasses import dataclass
from datetime import datetime, timezone
from enum import Enum
from pathlib import Path
from typing import Any

from openai import OpenAI
from dotenv import load_dotenv

# ── Paths ──────────────────────────────────────────────────────────────────

HUB_DIR = Path(__file__).resolve().parent.parent
load_dotenv(HUB_DIR / ".env")
TEMPLATE_PATH = HUB_DIR / "opencode.template.json"  # generated by n3rverberage init
CONFIG_PATH = HUB_DIR / "opencode.json"  # generated by this script
STATE_DIR = HUB_DIR / "scripts"
STATE_PATH = STATE_DIR / ".qwen_state.json"
TRACKING_PATH = HUB_DIR / "docs" / "stage-a-tracking.md"
CATALOG_PATH = HUB_DIR / "data" / "model-catalog.json"
DASHSCOPE_BASE_URL = "https://dashscope-intl.aliyuncs.com/compatible-mode/v1"
EXPIRATION_DATE = "2026-09-28"
TOTAL_TEXT_TOKENS = 103_000_000

# ── Enums & Data Classes ───────────────────────────────────────────────────


class Tier(Enum):
    CODER = 1
    FLAGSHIP = 2
    VALUE = 3
    THIRD_PARTY = 4
    ALPHA = 5


class ModelStatus(Enum):
    UNKNOWN = "UNKNOWN"
    ACTIVE = "ACTIVE"
    EXHAUSTED = "EXHAUSTED"
    SKIP = "SKIP"
    ERROR = "ERROR"


@dataclass
class ModelInfo:
    model_id: str
    tier: Tier
    priority: int
    status: ModelStatus = ModelStatus.UNKNOWN
    remaining_tokens: int | None = None


@dataclass
class RotationState:
    active_model_index: int
    active_model_id: str
    exhausted_set: list[str]
    last_rotation: str


@dataclass
class TrackingEntry:
    timestamp: str
    model_id: str
    action: str
    remaining_estimate: int = -1
    notes: str = ""


# ── MAGI Memory Integration ────────────────────────────────────────────────


def log_quota_to_magi(
    model_id: str,
    action: str,
    remaining_tokens: int | None = None,
    metadata: dict | None = None,
) -> None:
    """Log quota event to MAGI memory system.

    Parameters
    ----------
    model_id : str
        The model that was activated/exhausted/probed.
    action : str
        Event type: 'activate', 'exhaust', 'probe_ok', 'probe_fail', 'rotate'.
    remaining_tokens : int | None
        Remaining quota if available from API headers.
    metadata : dict | None
        Additional context (tier, rotation_index, etc.).
    """
    try:
        from n3rverberage.config import load_runtime_settings
        from n3rverberage.mcp.memory_service import MemoryService

        settings = load_runtime_settings(HUB_DIR)
        service = MemoryService(settings)
        topic_key = f"quota-{model_id}-{datetime.now(timezone.utc).strftime('%Y-%m-%d')}"

        content = {
            "model_id": model_id,
            "action": action,
            "remaining_tokens": remaining_tokens,
            "timestamp": datetime.now(timezone.utc).isoformat(),
            "metadata": metadata or {},
        }

        service.memory_save(
            topic_key=topic_key,
            title=f"Quota {action}: {model_id}",
            content=json.dumps(content, indent=2),
            type="config",
            scope="project",
        )
        print(f"  [MAGI] Logged quota event to memory: {topic_key}", file=sys.stderr)

    except ImportError:
        # n3rverberage not available - skip logging
        print(
            "  [MAGI] Skipping memory log (n3rverberage not installed)",
            file=sys.stderr,
        )
    except Exception as exc:
        # Don't fail the rotation - just warn
        print(
            f"  [MAGI] Warning: Failed to log to memory: {exc}",
            file=sys.stderr,
        )


# ── SKIP SET (10 models: 6 exhausted + 4 unsupported) ──────────────────────

SKIP_SET = frozenset(
    {
        # Exhausted (6)
        "qwen-plus",
        "qwen-max",
        "qwen-turbo",
        "qwen-flash",
        "deepseek-v4-pro",
        "deepseek-v4-flash",
        # Unsupported (4)
        "qwen3.7-plus",
        "qwen3.7-max",
        "qwen-plus-character-ja",
        "qwen-plus-2025-01-25",
        # Non-chat models (4) — different API, not usable via chat completions
        "qvq-max",  # visual reasoning, streaming-only
        "qwen-vl-ocr",  # OCR model, requires image input
        "qwen-vl-ocr-2025-11-20",  # OCR snapshot
        "wan2.2-kf2v-flash",  # video generation, not a chat model
    }
)

# ── Model Catalog (loaded from hub/data/model-catalog.json) ────────────────

_TIER_MAP: dict[int, Tier] = {
    1: Tier.CODER,
    2: Tier.FLAGSHIP,
    3: Tier.VALUE,
    4: Tier.THIRD_PARTY,
    5: Tier.ALPHA,
}


def _load_catalog() -> tuple[list[ModelInfo], list[str]]:
    """Load LLM models from catalog.json. Returns (MODELS, MODEL_IDS)."""
    if not CATALOG_PATH.exists():
        raise FileNotFoundError(
            f"Model catalog not found: {CATALOG_PATH}. "
            "Run validate-catalog.py or check data/model-catalog.json exists."
        )
    with open(CATALOG_PATH) as f:
        catalog = json.load(f)

    models: list[ModelInfo] = []
    for entry in catalog["models"]:
        tier_val = entry.get("tier", 0)
        if tier_val <= 0:
            continue  # skip non-LLM models (TTS, etc.)
        tier = _TIER_MAP.get(tier_val, Tier.ALPHA)
        mid = entry["model_id"]
        # Use skip flag from catalog for initial status
        status = ModelStatus.SKIP if entry.get("skip", False) else ModelStatus.UNKNOWN
        models.append(
            ModelInfo(
                model_id=mid,
                tier=tier,
                priority=entry.get("priority", 0),
                status=status,
            )
        )

    # Sort by tier then priority (matching original order)
    models.sort(key=lambda m: (m.tier.value, m.priority))
    model_ids = [m.model_id for m in models]
    return models, model_ids


MODELS, MODEL_IDS = _load_catalog()


# ── State Management ───────────────────────────────────────────────────────


def load_state() -> RotationState:
    """Load rotation state from disk, or initialize fresh."""
    if not STATE_PATH.exists():
        return _fresh_state()

    try:
        data = json.loads(STATE_PATH.read_text())
        return RotationState(**data)
    except (json.JSONDecodeError, TypeError, KeyError) as exc:
        print(
            f"WARNING: state file corrupted ({exc}), reinitializing.", file=sys.stderr
        )
        return _fresh_state()


def _fresh_state() -> RotationState:
    return RotationState(
        active_model_index=0,
        active_model_id=MODELS[0].model_id,
        exhausted_set=list(SKIP_SET),
        last_rotation=datetime.now(timezone.utc).isoformat(),
    )


def save_state(state: RotationState) -> None:
    """Write rotation state to disk."""
    STATE_DIR.mkdir(parents=True, exist_ok=True)
    STATE_PATH.write_text(
        json.dumps(
            {
                "active_model_index": state.active_model_index,
                "active_model_id": state.active_model_id,
                "exhausted_set": sorted(set(state.exhausted_set)),
                "last_rotation": state.last_rotation,
            },
            indent=2,
        )
    )


# ── Config Generator ────────────────────────────────────────────────────────


def generate_opencode(model_id: str, *, dry_run: bool = False) -> bool:
    """Read template, substitute {model}, write opencode.json.

    Returns True on success, False on failure.
    """
    if not TEMPLATE_PATH.exists():
        print(f"FATAL: {TEMPLATE_PATH} not found.", file=sys.stderr)
        print(
            "This file is generated by n3rverberage. Run: n3rverberage init",
            file=sys.stderr,
        )
        return False

    try:
        template = TEMPLATE_PATH.read_text()
        json.loads(template)  # validate JSON
    except json.JSONDecodeError as exc:
        print(f"FATAL: template not valid JSON: {exc}", file=sys.stderr)
        return False

    if "{model}" not in template:
        print("WARNING: template contains no {model} placeholder.", file=sys.stderr)

    output = template.replace("{model}", model_id)

    if "{model}" in output:
        print("ERROR: {model} still present after substitution.", file=sys.stderr)
        return False

    # Preserve {env:DASHSCOPE_API_KEY} — opencode resolves it at runtime

    if dry_run:
        print(f"  [DRY-RUN] Would write opencode.json with model=qwen/{model_id}")
        return True

    try:
        CONFIG_PATH.write_text(output)
        print(f"  Written opencode.json with model=qwen/{model_id}")
        return True
    except PermissionError as exc:
        print(f"ERROR: Cannot write {CONFIG_PATH}: {exc}", file=sys.stderr)
        return False


# ── Probe Engine ────────────────────────────────────────────────────────────


def get_client() -> OpenAI:
    """Create OpenAI client pointing at DashScope endpoint."""
    api_key = os.environ.get("DASHSCOPE_API_KEY")
    if not api_key:
        print("FATAL: DASHSCOPE_API_KEY not set.", file=sys.stderr)
        sys.exit(1)
    return OpenAI(api_key=api_key, base_url=DASHSCOPE_BASE_URL, timeout=10.0)


def probe_model(model_id: str, client: OpenAI) -> tuple[ModelStatus, int | None]:
    """Probe a single model via 1-token request.

    Tries enable_thinking=False first (handles most models).
    Retries with enable_thinking=True if the model requires it (thinking-only models).

    Returns (status, remaining_tokens).
    remaining_tokens is None if not available.
    """
    if model_id in SKIP_SET:
        return ModelStatus.SKIP, None

    for thinking_mode in (False, True):
        try:
            response = client.chat.completions.create(
                model=model_id,
                messages=[{"role": "user", "content": "."}],
                max_tokens=1,
                temperature=0,
                extra_body={"enable_thinking": thinking_mode},
            )
            remaining = _extract_remaining(response)
            return ModelStatus.ACTIVE, remaining

        except Exception as exc:
            error_str = str(exc)
            if "AllocationQuota.FreeTierOnly" in error_str:
                return ModelStatus.EXHAUSTED, 0
            if "401" in error_str or "Unauthorized" in error_str:
                print("FATAL: Invalid API key.", file=sys.stderr)
                sys.exit(1)
            # Thinking-only models: retry with enable_thinking=True
            if thinking_mode is False and "restricted to True" in error_str:
                continue
            return ModelStatus.ERROR, None

    return ModelStatus.ERROR, None


def _extract_remaining(response: Any) -> int | None:
    """Extract x-qwen-quota-remaining header from API response if present."""
    headers = getattr(response, "headers", None)
    if headers:
        val = headers.get("x-qwen-quota-remaining")
        if val is not None:
            try:
                return int(val)
            except (ValueError, TypeError):
                pass
    return None


# ── Tracking Writer ─────────────────────────────────────────────────────────


def write_tracking(state: RotationState, entries: list[dict] | None = None) -> None:
    """Write or rewrite docs/stage-a-tracking.md."""
    days_remaining = _days_until(EXPIRATION_DATE)
    active_count = sum(
        1
        for m in MODELS
        if m.model_id not in state.exhausted_set and m.model_id not in SKIP_SET
    )
    exhausted_count = len([m for m in MODELS if m.model_id in state.exhausted_set])
    skip_count = len(SKIP_SET)

    content = f"""# Qwen Free Quota Tracking

> **Started**: 2026-07-06 | **Expires**: {EXPIRATION_DATE} | **Days remaining**: {days_remaining}
> **Account**: Singapore International | **Total text quota**: {TOTAL_TEXT_TOKENS:,} tokens

## Summary

| Metric | Value |
|--------|-------|
| Total models (LLM) | {len(MODELS)} |
| Available | {active_count} |
| Exhausted | {exhausted_count} |
| Skipped | {skip_count} |
| Est. remaining tokens | ~{TOTAL_TEXT_TOKENS:,} |

## Activity Log

{_format_activity_log(entries)}

## Model Roster

| # | Tier | Model | Status | Initial Tokens |
|---|------|-------|--------|:---:|
{_format_roster(state)}
"""
    TRACKING_PATH.parent.mkdir(parents=True, exist_ok=True)
    TRACKING_PATH.write_text(content)


def _days_until(date_str: str) -> int:
    target = datetime.strptime(date_str, "%Y-%m-%d").replace(tzinfo=timezone.utc)
    now = datetime.now(timezone.utc)
    return max(0, (target - now).days)


def _format_activity_log(entries: list[dict] | None) -> str:
    lines = [
        "| Date | Model | Action | Est. Remaining | Notes |",
        "|------|-------|--------|:---:|-------|",
    ]
    if entries:
        for e in entries:
            ts = e.get("timestamp", "")[:10]
            rem = e.get("remaining_estimate", -1)
            rem_str = f"{rem:,}" if isinstance(rem, int) and rem >= 0 else "—"
            lines.append(
                f"| {ts} | {e['model_id']} | {e['action']} | {rem_str} "
                f"| {e.get('notes', '')} |"
            )
    return "\n".join(lines) + "\n"


def _format_roster(state: RotationState) -> str:
    lines = []
    for i, m in enumerate(MODELS):
        if m.model_id in SKIP_SET:
            status = "SKIP"
        elif m.model_id in state.exhausted_set:
            status = "EXHAUSTED"
        elif i == state.active_model_index:
            status = "ACTIVE"
        else:
            status = "UNKNOWN"
        lines.append(
            f"| {i + 1} | {m.tier.value} | {m.model_id} | {status} | 1,000,000 |"
        )
    return "\n".join(lines)


# ── Commands ────────────────────────────────────────────────────────────────


def cmd_status(args: argparse.Namespace) -> None:
    """Probe all 81 models, output availability table."""
    client = get_client()
    state = load_state()

    results: list[dict] = []
    active_count = 0
    exhausted_count = 0
    skip_count = 0
    error_count = 0
    estimated_remaining = 0
    headers_seen = 0
    new_exhausted: list[str] = []

    print(f"Probing {len(MODELS)} models...\n", file=sys.stderr)

    for i, model in enumerate(MODELS):
        mid = model.model_id

        if mid in SKIP_SET:
            results.append({"model": mid, "status": "SKIP", "remaining": None})
            skip_count += 1
            continue

        if mid in state.exhausted_set:
            results.append({"model": mid, "status": "EXHAUSTED", "remaining": 0})
            exhausted_count += 1
            continue

        print(f"  [{i + 1}/{len(MODELS)}] {mid} ... ", end="", file=sys.stderr)
        sys.stderr.flush()

        status, remaining = probe_model(mid, client)

        if status == ModelStatus.ACTIVE:
            active_count += 1
            if remaining is not None:
                estimated_remaining += remaining
                headers_seen += 1
            results.append({"model": mid, "status": "ACTIVE", "remaining": remaining})
            print("ACTIVE", file=sys.stderr)
        elif status == ModelStatus.EXHAUSTED:
            exhausted_count += 1
            new_exhausted.append(mid)
            results.append({"model": mid, "status": "EXHAUSTED", "remaining": 0})
            print("EXHAUSTED", file=sys.stderr)
        else:
            error_count += 1
            results.append({"model": mid, "status": "ERROR", "remaining": None})
            print("ERROR", file=sys.stderr)

    # Persist newly discovered exhausted models
    if new_exhausted:
        state.exhausted_set.extend(new_exhausted)
        save_state(state)

    active_model = MODELS[state.active_model_index]

    if args.json:
        output = {
            "summary": {
                "total": len(MODELS),
                "active": active_count,
                "exhausted": exhausted_count,
                "skipped": skip_count,
                "errors": error_count,
            },
            "models": results,
            "active_model": active_model.model_id,
            "active_tier": active_model.tier.name,
            "estimated_remaining": estimated_remaining if headers_seen > 0 else None,
            "quota_header_available": headers_seen > 0,
        }
        print(json.dumps(output, indent=2))
    else:
        print(f"\n{'Model':50s} {'Status':15s} {'Remaining':>10s}")
        print("-" * 78)
        for r in results:
            rem = (
                f"{r['remaining']:>10,}"
                if isinstance(r.get("remaining"), int)
                else "         —"
            )
            print(f"{r['model']:50s} {r['status']:15s} {rem}")
        print("-" * 78)
        print(
            f"Summary: {active_count}/{len(MODELS)} available, "
            f"{exhausted_count} exhausted, {skip_count} skipped, "
            f"{error_count} errors"
        )
        print(f"Active model: {active_model.model_id} (Tier {active_model.tier.value})")
        if headers_seen > 0:
            print(f"Est. remaining: ~{estimated_remaining:,} tokens")
        else:
            print("Est. remaining: N/A (header not available on this endpoint)")

    if active_count == 0 and error_count == len(MODELS):
        print("Cannot reach DashScope API.", file=sys.stderr)
        sys.exit(1)
    if active_count == 0:
        print("0/81 models available.", file=sys.stderr)
        sys.exit(1)
    sys.exit(0)


def cmd_rotate(args: argparse.Namespace) -> None:
    """Test active model; if exhausted, switch to next; regen opencode.json."""
    state = load_state()

    # --model override: set directly, skip probing
    if args.model:
        for i, m in enumerate(MODELS):
            if m.model_id == args.model:
                state.active_model_index = i
                state.active_model_id = m.model_id
                state.last_rotation = datetime.now(timezone.utc).isoformat()
                if not args.dry_run:
                    generate_opencode(m.model_id, dry_run=False)
                    save_state(state)
                    # Log to MAGI: manual model activation
                    log_quota_to_magi(
                        model_id=m.model_id,
                        action="activate",
                        remaining_tokens=None,
                        metadata={
                            "tier": m.tier.value,
                            "rotation_index": i,
                            "manual_override": True,
                        },
                    )
                print(f"Set active model to {m.model_id} (Tier {m.tier.value}).")
                return
        print(f"ERROR: Model '{args.model}' not found in catalog.", file=sys.stderr)
        sys.exit(1)

    # Probe current active model
    current = MODELS[state.active_model_index]

    if not args.dry_run:
        client = get_client()
        if not args.force:
            print(f"Probing current model {current.model_id} ... ", end="")
            sys.stdout.flush()
            status, remaining = probe_model(current.model_id, client)
            if status == ModelStatus.ACTIVE:
                print(f"ACTIVE (remaining={remaining})")
                if remaining is not None:
                    current.remaining_tokens = remaining
                print("No rotation needed.")
                return
            elif status == ModelStatus.EXHAUSTED:
                print("EXHAUSTED")
                if current.model_id not in state.exhausted_set:
                    state.exhausted_set.append(current.model_id)
            elif status == ModelStatus.ERROR:
                print("ERROR (will try next model)")
    else:
        client = None  # dry-run: no API calls

    # Find next available model
    found_model: ModelInfo | None = None
    for i in range(state.active_model_index + 1, len(MODELS)):
        candidate = MODELS[i]
        if candidate.model_id in SKIP_SET:
            continue
        if candidate.model_id in state.exhausted_set:
            continue

        if args.dry_run:
            print(f"  [DRY-RUN] Would probe {candidate.model_id} ... ACTIVE (assumed)")
            found_model = candidate
            break

        print(f"  Probing {candidate.model_id} ... ", end="")
        sys.stdout.flush()
        assert client is not None  # dry-run exits loop before reaching here
        status, _ = probe_model(candidate.model_id, client)

        if status == ModelStatus.ACTIVE:
            print("ACTIVE")
            found_model = candidate
            break
        elif status == ModelStatus.EXHAUSTED:
            print("EXHAUSTED")
            state.exhausted_set.append(candidate.model_id)
            continue
        else:
            print("ERROR")
            continue

    if found_model is None:
        probable = len(MODELS) - len([m for m in MODELS if m.model_id in SKIP_SET])
        print(
            f"\nCRITICAL: All {probable} probed models exhausted. Preserving opencode.json.",
            file=sys.stderr,
        )
        save_state(state)
        sys.exit(1)

    # Update state
    state.active_model_index = MODEL_IDS.index(found_model.model_id)
    state.active_model_id = found_model.model_id
    state.last_rotation = datetime.now(timezone.utc).isoformat()

    # Log to MAGI: exhaustion of previous model
    if not args.dry_run:
        log_quota_to_magi(
            model_id=current.model_id,
            action="exhaust",
            remaining_tokens=0,
            metadata={
                "tier": current.tier.value,
                "rotation_index": state.active_model_index,
                "reason": "AllocationQuota.FreeTierOnly",
            },
        )

        # Log to MAGI: activation of new model
        log_quota_to_magi(
            model_id=found_model.model_id,
            action="activate",
            remaining_tokens=None,  # Will be discovered on first use
            metadata={
                "tier": found_model.tier.value,
                "rotation_index": state.active_model_index,
                "previous_model": current.model_id,
            },
        )

    # Regenerate opencode.json
    print("Regenerating opencode.json from template. Manual edits will be lost.")
    if not args.dry_run:
        ok = generate_opencode(found_model.model_id, dry_run=False)
        if not ok:
            sys.exit(1)
        save_state(state)
    else:
        generate_opencode(found_model.model_id, dry_run=True)

    print(
        f"Rotated to {found_model.model_id} (Tier {found_model.tier.value}). "
        f"opencode.json updated."
    )


def cmd_track(args: argparse.Namespace) -> None:
    """Update docs/stage-a-tracking.md from current state (no probing)."""
    state = load_state()

    entries: list[dict] = [
        {
            "timestamp": state.last_rotation,
            "model_id": state.active_model_id,
            "action": "activate",
            "remaining_estimate": -1,
            "notes": "Current active model",
        },
    ]

    for mid in state.exhausted_set:
        if mid not in SKIP_SET:
            entries.append(
                {
                    "timestamp": state.last_rotation,
                    "model_id": mid,
                    "action": "exhaust",
                    "remaining_estimate": 0,
                    "notes": "",
                }
            )

    write_tracking(state, entries)
    print(f"Tracking doc written to {TRACKING_PATH}")


# ── CLI Entry Point ────────────────────────────────────────────────────────


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Qwen Model Fallback Rotator for opencode",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=(
            "Examples:\n"
            "  %(prog)s --status           # Probe all models, table output\n"
            "  %(prog)s --status --json    # Probe all models, JSON output\n"
            "  %(prog)s --rotate           # Rotate to next available model\n"
            "  %(prog)s --rotate --force   # Force rotate (skip probe)\n"
            "  %(prog)s --rotate --model qwen3-coder-flash  # Set model\n"
            "  %(prog)s --rotate --dry-run # Preview rotation\n"
            "  %(prog)s --track            # Update tracking doc\n"
        ),
    )
    parser.add_argument(
        "--status",
        action="store_true",
        help="Probe all models, output availability table",
    )
    parser.add_argument(
        "--rotate",
        action="store_true",
        help="Test active model; if exhausted, switch to next",
    )
    parser.add_argument(
        "--track",
        action="store_true",
        help="Update tracking doc from current state (no probing)",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Force rotation regardless of current model status",
    )
    parser.add_argument(
        "--json", action="store_true", help="Output as JSON (for automation)"
    )
    parser.add_argument(
        "--model", type=str, help="Override active model directly, skip rotation"
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Show what would happen without touching files",
    )

    args = parser.parse_args()

    # Default: --status --json (when no command flag given)
    if not (args.status or args.rotate or args.track):
        args.status = True
        args.json = True

    if args.status:
        cmd_status(args)
    elif args.rotate:
        cmd_rotate(args)
    elif args.track:
        cmd_track(args)


if __name__ == "__main__":
    main()
